# Generated by Django 5.1 on 2024-08-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_booking_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
