# Generated by Django 5.1 on 2024-08-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_booking_payment_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_deadline',
            field=models.DateTimeField(),
        ),
    ]
