# Generated by Django 5.1 on 2024-08-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
    ]
