# Generated by Django 5.1 on 2024-08-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_payment_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='amenity/'),
        ),
    ]
