# Generated by Django 5.1 on 2024-08-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_payment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='hotel_images',
            field=models.FileField(upload_to='hotelroom/'),
        ),
    ]
