# Generated by Django 5.1.1 on 2024-09-16 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_booking_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelroom',
            name='is_booked',
        ),
        migrations.CreateModel(
            name='HotelRoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.booking')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotelroom')),
            ],
        ),
    ]
