# Generated by Django 5.1.1 on 2024-09-18 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_hotelroom_is_booked_hotelroombooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelRoomBooking',
        ),
    ]
