# Generated by Django 5.1 on 2024-09-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_delete_hotelroombooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
