# Generated by Django 5.1 on 2024-09-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_hotelroom_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='rating',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
