# Generated by Django 5.1 on 2024-10-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_hotelroom_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
